Repository mattermost/mattermost-plugin-legal-hold, pull requests merged in 2024-09, with the labels that each got.

#99 fix: don't check for check compliance settings for s3 config
  server/api.go
  server/plugin.go
Labels: 3: QA Review

#101 feat: hmac hashing
  .gitignore
  processor/README.md
  processor/cmd/root.go
  processor/model/hash.go
  processor/parse/hash.go
  server/legalhold/legal_hold.go
  server/legalhold/legal_hold_test.go
  webapp/src/components/legal_hold_table/legal_hold_row/eye-outline_F06D0.svg
  webapp/src/components/legal_hold_table/legal_hold_row/legal_hold_row.tsx
  webapp/src/components/legal_hold_table/legal_hold_table.tsx
  webapp/src/components/legal_holds_setting.tsx
  webapp/src/components/show_secret_modal.tsx
  webapp/src/types/index.d.ts
Labels: 3: QA Review

#102 fix: including public channels should check for compliance settings
  server/api.go
  server/model/legal_hold.go
  server/model/legal_hold_test.go
  server/store/kvstore/legal_hold.go
  server/store/kvstore/legal_hold_test.go
Labels: 3: QA Review

#104 chore: use put instead of post for update
  server/api.go
  webapp/src/client.ts
Labels: 3: QA Review

#97 Initial playwright setup for e2e tests
  .github/workflows/playwright.yml
  .github/workflows/processor-release.yml
  .gitignore
  .nvmrc
  e2e/playwright/.eslintignore
  e2e/playwright/.eslintrc.json
  e2e/playwright/.gitignore
  e2e/playwright/.prettierignore
  e2e/playwright/.prettierrc.json
  e2e/playwright/README.md
  e2e/playwright/package-lock.json
  e2e/playwright/package.json
  e2e/playwright/playwright.config.ts
  e2e/playwright/setup-environment
  e2e/playwright/support/constant.ts
  e2e/playwright/tests/legalhold_plugin.spec.ts
  e2e/playwright/tests/test.setup.ts
  e2e/playwright/tsconfig.json
Labels: 2: Dev Review

#108 ci: update playwright workflow
  .github/workflows/playwright.yml
Labels: 2: Dev Review

#110 [MM-796] Added download attribute to download button
  webapp/src/components/legal_hold_table/legal_hold_row/legal_hold_row.tsx
Labels: 2: Dev Review, 3: QA Review

#112 ci: update playwright job
  .github/workflows/playwright.yml
  e2e/playwright/package-lock.json
  e2e/playwright/package.json
Labels: 2: Dev Review
